### PR TITLE
Remove reserve factor and interest rate model.

### PR DESCRIPTION
**Pull request by piobab**
reserve_factor and interest_rate_model stay in Red Bank

### CODE REVIEW

**Review by grod220 — APPROVED** [review]

**Comment by grod220** [comment]
Can you rebase to latest master and update the version btw? https://crates.io/crates/mars-params

**Comment by piobab** [comment]
> Can you rebase to latest master and update the version btw? https://crates.io/crates/mars-params

Can't update crates.io. Don't have access to this crate.

**Comment by grod220** [comment]
@brimigs can you give that crate's access to both me and piotr?

**Comment by brimigs** [comment]
> @brimigs can you give that crate's access to both me and piotr?

invite send 👍

**Pull request merged**
